# Generated by Django 2.1.4 on 2019-02-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('id_user_in_telegram', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryClothe',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPrice',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('img_center', models.ImageField(upload_to='bot_media')),
                ('img_inline', models.ImageField(upload_to='bot_media')),
                ('img_bottom', models.ImageField(upload_to='bot_media')),
                ('created', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('markup', models.PositiveSmallIntegerField()),
                ('link_partner_to_product', models.URLField(max_length=1024)),
                ('link_image_to_product', models.URLField(max_length=1024)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryClothe')),
            ],
        ),
        migrations.CreateModel(
            name='ClotheCountry',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClotheMale',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClothePartner',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryUpdate',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('update_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('quantity_of_goods', models.PositiveSmallIntegerField(default=1)),
                ('first_name', models.CharField(max_length=150)),
                ('markup', models.PositiveSmallIntegerField(default=0, null=True)),
                ('price', models.PositiveSmallIntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('post_office', models.CharField(max_length=150, null=True)),
                ('department', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('size', models.CharField(max_length=30, null=True)),
                ('tnt', models.CharField(max_length=30, null=True)),
                ('have_ordered', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.Clothe')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPhoto',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='bot_media')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('id_user_in_telegram', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.User'),
        ),
        migrations.AddField(
            model_name='male',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tgbot.User'),
        ),
        migrations.AddField(
            model_name='country',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tgbot.User'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.ClotheCountry'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryPrice'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='male',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.ClotheMale'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.ClothePartner'),
        ),
    ]
