# Generated by Django 2.1.4 on 2018-12-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('callback_data', models.CharField(max_length=30)),
                ('switch_inline_query_current_chat', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryClothes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPrice',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('img_top', models.ImageField(upload_to='product_top')),
                ('img_left', models.ImageField(upload_to='product_left')),
                ('img_right', models.ImageField(upload_to='product_right')),
                ('img_bottom', models.ImageField(upload_to='product_bottom')),
                ('created', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryClothes')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryPrice')),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryPrice')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategoryClothes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('id_user_in_telegram', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.Country'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.CategoryPrice'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='male',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.Male'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.ParentCategoryClothes'),
        ),
        migrations.AddField(
            model_name='categoryclothes',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.ParentCategoryClothes'),
        ),
        migrations.AddField(
            model_name='basket',
            name='product_id',
            field=models.ManyToManyField(to='tgbot.Clothes'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user_id',
            field=models.ManyToManyField(to='tgbot.User'),
        ),
    ]
