# Generated by Django 2.1.4 on 2019-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothepartner',
            name='markup_url',
            field=models.URLField(default='http://export.admitad.com/ua/webmaster/websites/1003946/products/export_adv_products/?feed_id=14558&code=o7b8n000cs&user=kolb&template=40577'),
            preserve_default=False,
        ),
    ]
